name: Github commit action
on: [push]
jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: x64
      - name: Install flake8
        run: pip install flake8
      - name: Install requirements
        run: ls -latr
      - name: Install requirements2
        run: ls; pip install -r requirements.txt
      - name: Run flake8
        run: flake8
        working-directory: ./passworder
      - name: Run unittests
        run: python -m unittest discover .
