name: Github commit action
on: [push]
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: x64
      - name: Install flake8
        run: pip install flake8
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Linting with Flake8
        run: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unittests
        run: python3 -m unittest discover .

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.USER_NAME}}
          DOCKER_PASSWORD: ${{secrets.PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Building the docker image
        run: docker build -t passworder .
      - name: Push image to hub.docker.com
        run: docker push ${{secrets.DOCKER_USER}}/ci_fastapi_passworder

      # The next steps should be added by you!
      # - Build the docker image
      # - Push the docker image to hub.docker.com (you'll need an account there!)